### ISSUE TITLE
Formatting lessons

### ISSUE THREAD

**Issue by karawoo** [karawoo/2015-04-27-wsu#24]
Last weekend Greg helpfully fixed the issue that was causing our `syllabus/index.html` page to be formatted incorrectly. I have been trying to get the lesson pages formatted to match those of the standard Software Carpentry lessons ([like this](http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data.html)) by modifying the makefile from that repo, but I don't actually know how to use make and can't figure this out, even when I try moving all the lessons/tools/etc. to the root of the repository. Right now if I run `knit2html()` on the RMarkdown files we get HTML that looks like this:

![html_preview](https://cloud.githubusercontent.com/assets/4452678/7283793/e056f20a-e8ed-11e4-9247-f25cc2f0ea4f.png)

This isn't as nice, especially with the `{.objectives}` showing up, but is it good enough, @kbroman? I'm inclined to say yes because I can't bear the thought of fighting with the formatting any longer. I'd like to have the HTML pages available to teach from and for any learners who might need to use assistive devices. 

If this is ok then I will put together a pull request with an updated `syllabus/index.md`, rendered lessons, and a page for the capstone exercise.

**Comment by kbroman** [comment]
I think it's good enough for now. You and I are the only ones to look at these until afterwards, right?

I'd like to figure it out, but I feel like I should be focusing on finishing the lessons first.

**Comment by karawoo** [comment]
I had thought I would send one more email to the learners and include a link to the lessons, being clear that they don't need to look at them but can if they're interested. If anyone uses assistive technology on their laptop due to vision impairments they may want to access lessons beforehand, and the accessibility statement mentions that they will be available. For that purpose, I don't think the formatting issues are critical.

**Comment by kbroman** [comment]
Seems like there are pandoc templates plus some sort of python-based filters (which handle the `.objectives` and such). I'll take a stab at it.

**Comment by kbroman** [comment]
I'm going to start by seeing if I compile [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation) locally. Then I'll try to transfer that to our repository.

I was initially getting errors, but they seemed to be due to not having a couple of python modules (namely `CommonMark` and `pandocfilters`); the error messages weren't super helpful, but [this comment](https://github.com/swcarpentry/lesson-template/issues/107#issuecomment-73037527) in an issue for the [lesson template](https://github.com/swcarpentry/lesson-template) was informative.

**Comment by kbroman** [comment]
I think I have it. Not sure it's quite the right thing to do, since we've got stuff in `syllabus`, but in my [`compile_lessons`](https://github.com/kbroman/2015-04-27-wsu/tree/compile_lessons) branch, if you go into `syllabus` and type

```
make ggplot2.html
```

It compiles `ggplot2.Rmd` → `ggplot2.md` → `ggplot2.html` and that last file seems to look like what we want.

**Comment by kbroman** [comment]
See PR #27.
